# Generated by Django 5.1 on 2024-09-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
