# Generated by Django 5.1 on 2024-10-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from_page', '0002_student_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=50)),
                ('course_fees', models.FloatField()),
                ('course_duration', models.DurationField(max_length=6)),
            ],
        ),
    ]
